#!/bin/bash

# This file is completely based on one in the neutron repository here:
# https://opendev.org/openstack/neutron/src/branch/master/devstack/lib/l3_agent

function configure_l3_agent {
    iniset $Q_L3_CONF_FILE agent extensions "$L3_AGENT_EXTENSIONS"
}
